### ISSUE TITLE
git operations using a username in URL lead to HTTP 500

### ISSUE THREAD

**Issue by sebhof** [gogs/gogs#6150]
**Describe the bug**
Performing a git command while giving only the username in the git URL leads to a 500 server error instead of asking for the users password

**Gogs version and commit**
0.11.91-158858931

**Git version**

```
$ git version 2.11.0
```

**Operating system**
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.12 (stretch)
Release:	9.12
Codename:	stretch

**Database**
postgresql               9.6+181+deb9u3

**To Reproduce**
1. In a terminal run
```
git clone http://user@host:6000/repo.git
```

**Can you reproduce the bug at https://try.gogs.io?**
No. The git clone command here asks for a password as expected.

**Expected behavior**
git should ask for a password. I think the server should a return a 401 in this case?

**Actual behavior**
Server returns a 500:
```
fatal: unable to access 'http://user@host:6000/repo.git/': The requested URL returned error: 500
```
In the log I see:
```
2020/05/07 10:05:38 [TRACE] authentication failed for 'XXX' with empty password
2020/05/07 10:05:38 [ERROR] [...gogs/internal/route/repo/http.go:127 func1()] Failed to authenticate user [name: XXX]: authenticate via login source: user does not exist: map[login:XXX]
```

**Additional context**
We ran into this issue since the Netbeans IDE stores the username in the .git/config file as part of the url. We recently updated gogs to 0.11.91 and are now unable to use the git feature in Netbeans anymore. Please let me know if I can provide more information. Thanks.

**Comment by unknwon** [comment]
Hi, this error log does not look like you're running 0.11.91.

>2020/05/07 10:05:38 [ERROR] [...gogs/internal/route/repo/http.go:127 func1()] Failed to authenticate user [name: XXX]: authenticate via login source: user does not exist: map[login:XXX]

Please report the version show on your admin dashboard (`/admin`).

**Comment by sebhof** [comment]
Interesting... I installed the Debian-Package from
```
deb https://dl.packager.io/srv/deb/gogs/gogs/master/debian 9 main
```
dpkg told me, 0.11.91-1588589312.9fd4f is installed.

But in the /admin I see:
```
Anwendungsversion
    0.12.0+dev
Git-Version
    2.11.0
Go-Version
    go1.14.2
Build-Zeit
Build-Commit
    N/A 
```

**Comment by unknwon** [comment]
Thanks! Anyway, looks like a bug, will fix before 0.12 release.

**Comment by sebhof** [comment]
Thanks! Let me know if additional input is required.

**Comment by unknwon** [comment]
@sebhof: Hi! Getting back to you on this problem, I think the (same) reason you're not able to reproduce on https://try.gogs.io and myself locally is that the underlying error checking bug has been fixed at some point after the version you're currently using.

Would you be able to upgrade your installation see if the problem still presents? Thanks!

**Comment by sebhof** [comment]
Hi, sorry for my late response. I updated gogs from the Debian repository to version 0.11.91-1598167677.afb445bb.stretch (0.13.0+dev on /admin page). Unfortunately the error still exists. Same behaviour as before. 

But in the meantime we use another workflow and other tools, so that we are not affected by this error anymore. Perhaps it is a special problem in our installation and if no one else is affected, I think we should keep this bug closed.

Thanks for your assistance! Regards
